name: Deploy Laboratorio Final DevSecOps / Staging
on:
  push:
    branches:
      - staging
jobs:
  # Ejecutar SAST -> Usar SonarCloud o herramienta similar.
  check-sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v4.0.0 # Ex: v4.0.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  # Ejecutar SCA ->Usar Dependency Check o similar.
  check-sca:
    runs-on: ubuntu-latest
    needs: check-sast
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  # Construcci칩n de la Imagen Docker.
  build-image:
    runs-on: ubuntu-latest
    needs: check-sca
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        id: build-image
        run: |
          ls -l
          docker build -f Dockerfile -t nombre:tag
          echo "Construcci칩n de la Imagen Docker"
  # Image Security -> Usar Trivy o similar.
  check-image-security:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  # An치lisis DAST -> Usar Owasp ZAP o similar
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    needs: check-image-security
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: staging
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://staging.localhost'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
  # Despliegue de la aplicaci칩n -> Puede utilizar Minikube o Docker de su equipo(notebook).
  deploy-container:
    runs-on: ubuntu-latest
    needs: zap_scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        id: build-image
        run: |
          ls -l
          docker build -f Dockerfile -t nombre:tag
