name: Deploy Laboratorio Final DevSecOps / Staging
on:
  push:
    branches:
      - staging
env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/devsecops-lab-final      
jobs:
  # Ejecutar SAST -> Usar SonarCloud o herramienta similar.
  check-sast:
    runs-on: ubuntu-latest
    name: Exec SAST
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2.0.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  # Ejecutar SCA ->Usar Dependency Check o similar.
  check-sca:
    runs-on: ubuntu-latest
    name: Exec SCA
    needs: check-sast
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  # Construcción de la Imagen Docker.
  build-image:
    runs-on: ubuntu-latest
    name: Build Docker Image
    needs: [check-sast, check-sca]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .
      - name: Push Docker Image
        run: docker push $IMAGE_NAME:${{ github.sha }}
  # Image Security -> Usar Trivy o similar.
  check-image-security:
    runs-on: ubuntu-latest
    name: Image Security
    needs: build-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  # Análisis DAST -> Usar Owasp ZAP o similar
  zap_scan:
    runs-on: self-hosted
    name: Exec DAST
    needs: check-image-security
    steps:
      - name: Build Docker Image
        id: build-image
        run: |
          docker run -d -p 8080:80 --name devsecops-app $IMAGE_NAME:${{ github.sha }}
      - name: Sleep
        run: |
          sleep 30
      - name: OWASP ZAP
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8080/'